-- 2019.07.11 GUESTBOOK DDL

CREATE TABLE GUESTBOOK_MESSAGE (
    MESSGE_ID NUMBER(6) CONSTRAINT GM_MID_PK PRIMARY KEY,
    GUEST_NAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    MESSAGE BLOB NOT NULL
);

CREATE SEQUENCE GM_MID_SEQ;

INSERT INTO GUESTBOOK_MESSAGE (MESSGE_ID, GUEST_NAME, PASSWORD, MESSAGE) 
values (GM_MID_SEQ.nextval);









